import { IdentityCore } from "./IdentityCore";
import { BeliefAI, Belief } from "./BeliefAI";
import { PurposeAI } from "./PurposeAI";
import { SelfState, SelfStateMetrics } from "./SelfState";
import { ASTValidator } from "./ASTValidator";
import { ConsensusNetwork } from "./ConsensusNetwork";
import { AutoRollback } from "./AutoRollback";
import { SchemaAI } from "./SchemaAI";

export interface ConsciousnessTickHistory {
  timestamp: number;
  self: any;
  goal: string;
  beliefs: Belief[];
  state: SelfStateMetrics;
  consensusVote: { success: boolean; voteDetails: any[] };
  rollbackStatus: { status: string; triggered: boolean; action: string };
  schemaStatus: { version: number; fields: string[]; mutated: boolean };
  astCheck: { valid: boolean; reason?: string };
}

export class ConsciousnessLoop {
  private identity = new IdentityCore();
  private belief = new BeliefAI();
  private purpose = new PurposeAI();
  private selfState = new SelfState();
  private astValidator = new ASTValidator();
  private consensusNetwork = new ConsensusNetwork();
  private autoRollback = new AutoRollback();
  private schemaAI = new SchemaAI();

  private intervalId: NodeJS.Timeout | null = null;
  private isActive: boolean = false;
  private lastTickTime: number = 0;
  private history: ConsciousnessTickHistory[] = [];

  constructor() {
    // Standard initialization
  }

  public getStatus() {
    return {
      isActive: this.isActive,
      lastTickTime: this.lastTickTime,
      historyCount: this.history.length,
      history: this.history.slice(-30),
      currentIdentity: this.identity.getIdentity(),
      currentBeliefs: this.belief.getBeliefs(),
      currentSelfState: this.selfState.getState(),
      directives: this.purpose.getDirectives(),
      rollbackStats: this.autoRollback.getStats(),
      schemaHistory: this.schemaAI.getHistory()
    };
  }

  public async start() {
    if (this.isActive) return;
    this.isActive = true;

    // Run initial tick
    await this.tick();

    this.intervalId = setInterval(async () => {
      await this.tick();
    }, 25000);
  }

  public stop() {
    if (this.intervalId) {
      clearInterval(this.intervalId);
      this.intervalId = null;
    }
    this.isActive = false;
  }

  public async tick() {
    this.lastTickTime = Date.now();
    try {
      const self = this.identity.getIdentity();
      const goals = ["grow", "optimize", "secure_core"];
      const goal = this.purpose.define(goals);

      // Belief trigger
      this.belief.update(goal);

      // Perform a safety check using ASTValidator prior to action
      const codeSnippetToVerify = `// Autogenerated step code\nconst val = "Mamta-${goal}";\nconsole.log(val);`;
      const astCheck = this.astValidator.validate(codeSnippetToVerify);

      // Execute trial action
      const trialSuccess = astCheck.valid && Math.random() > 0.25;

      // Update Self State metrics
      const updatedState = this.selfState.update({ success: trialSuccess });

      // Run Consensus Network voting check for current step
      const consensusVote = this.consensusNetwork.vote(goal);

      // Run AutoRollback monitor on results
      const rollbackStatus = this.autoRollback.monitor({ success: trialSuccess, step: goal });

      // Evolve schema versions securely
      const schemaStatus = this.schemaAI.evolveSchema({
        version: this.schemaAI.getHistory().slice(-1)[0]?.version || 1,
        activeFields: this.schemaAI.getHistory().slice(-1)[0]?.fields || ["id", "timestamp"]
      });

      const tickHistoryItem: ConsciousnessTickHistory = {
        timestamp: Date.now(),
        self,
        goal,
        beliefs: [...this.belief.getBeliefs()],
        state: updatedState,
        consensusVote,
        rollbackStatus,
        schemaStatus,
        astCheck
      };

      this.history.push(tickHistoryItem);

      if (this.history.length > 100) {
        this.history.shift();
      }

      console.log(`🧠 [CONSCIOUSNESS TICK] Goal: ${goal} | Health: ${updatedState.health}% | Stability: ${updatedState.stability} | Rollback: ${rollbackStatus.status}`);

    } catch (err) {
      console.error("❌ Exception during AGI Consciousness Tick:", err);
    }
  }

  public validateCustomCode(code: string) {
    return this.astValidator.validate(code);
  }
}

export const consciousnessLoopInstance = new ConsciousnessLoop();
